askomics/askomics

- .travis.yml
- requirements.txt
There are very few tests, but with this commit, we will use travis-ci.org to perform continuous integration
> Add continuous integration

- askomics/libaskomics/SourceFileConvertor.py
No logic changes, only superficial rewriting. I'm trying to wrap my head around
the code, anticipating a more in depth rewrite of the importing code (after deliberations).
> Code cleanning in SourceFileConvertor.

- .travis.yml
- README.md
- askomics/ask_view.py
- askomics/libaskomics/TripleStoreExplorer.py
- askomics/libaskomics/graph/Link.py
- askomics/libaskomics/integration/AbstractedEntity.py
- askomics/libaskomics/integration/AbstractedRelation.py
- askomics/libaskomics/rdfdb/QueryLauncher.py
- askomics/libaskomics/rdfdb/ResultsBuilder.py
- askomics/libaskomics/rdfdb/SparqlQueryBuilder.py
- askomics/libaskomics/source_file/SourceFile.py
- askomics/libaskomics/utils.py
- askomics/sparql/getClassInfoFromAbstractionQuery.sparql
- askomics/sparql/hasCategoryQuery.sparql
- askomics/sparql/initialQuery.sparql
- askomics/sparql/neighborHierarchyQuery.sparql
- askomics/sparql/neighborQuery.sparql
- askomics/sparql/neighborQueryFollowingShortcuts.sparql
- askomics/sparql/settingQuery.sparql
- requirements.txt
#6 rebased on master.
> Rewrite QueryBuilder to use python string.Template engine and iterator.
> Query builder refactoring

- askomics/libaskomics/rdfdb/SparqlQueryBuilder.py
> Document a perf tweak

- startAskomics.sh
Follow up of #17, forgot to commit a script
> Add missing script

- Dockerfile
- startAskomics.sh
> Fix venv stuff

- configs/production.agraph.ini
- configs/production.fuseki.ini
- configs/production.ini
- configs/production.virtuoso.ini
> Fix crash in prod mode

- askomics/static/js/AskomicsForceLayoutManager.js
> - create a positionable link between the same kind of node

- askomics/ask_view.py
- askomics/libaskomics/source_file/SourceFile.py
- askomics/static/js/AskomicsAttributesView.js
- askomics/static/js/AskomicsForceLayoutManager.js
- askomics/static/js/AskomicsGraphBuilder.js
- askomics/static/js/AskomicsLinksView.js
- askomics/static/js/MainAskomics.js
- askomics/templates/index.pt
- askomics/test/source_file_test.py
Some bugfix: 
New features:
TODO:
(only a link or a node selected (and colored in red) at a time)
> Bugfix and new features

- askomics/static/css/style.css
- askomics/static/js/AskomicsForceLayoutManager.js
- askomics/templates/index.pt
> Full Screen graph !

- askomics/static/js/AskomicsForceLayoutManager.js
- askomics/static/js/AskomicsGraphBuilder.js
- askomics/static/js/AskomicsLinksView.js
- askomics/static/js/query-handler.js
> [WIP] positionable query + UI improvment

- askomics/static/js/AskomicsForceLayoutManager.js
- askomics/static/js/AskomicsGraphBuilder.js
- askomics/static/js/AskomicsLinksView.js
> BUGFIX + double arrow for overlap query

- askomics/static/js/AskomicsAttributesView.js
- askomics/static/js/AskomicsForceLayoutManager.js
- askomics/static/js/AskomicsLinksView.js
- askomics/static/js/AskomicsMenuView.js
- askomics/static/js/AskomicsUserAbstraction.js
- askomics/static/js/MainAskomics.js
- launchAskomics-dev.sh
> - use link id (remove source-id.target.id-linkindex construction)

- askomics/libaskomics/source_file/SourceFile.py
- askomics/static/js/AskomicsAttributesView.js
- askomics/static/js/AskomicsGraphBuilder.js
- askomics/static/js/AskomicsLinksView.js
- askomics/static/js/MainAskomics.js
- askomics/static/js/integration.js
- askomics/static/js/query-handler.js
- askomics/templates/index.pt
- askomics/test/source_file_test.py
[WIP: don't merge now]
I made some improvements  in response to user feedback this morning:
* Empty values are considered as numeric values
* This function is triggered when user click on the reset button and at database deletion
* When user upload a new file, results table is emptied
* Compute stats at user demand
* When user upload a new file, stats are cleared
new database tab:
With the confirmation button
> [WIP] Bugfixes and improvments

- README.md
> change branch for travis/coverall icons

- Dockerfile
I will merge this now as Fabrice needs this
> Fix for docker

- askomics/ask_view.py
- askomics/libaskomics/ParamManager.py
- askomics/libaskomics/Security.py
- askomics/libaskomics/TripleStoreExplorer.py
- askomics/libaskomics/rdfdb/SparqlQueryAuth.py
- askomics/libaskomics/rdfdb/SparqlQueryBuilder.py
- askomics/libaskomics/rdfdb/SparqlQueryGraph.py
- askomics/libaskomics/rdfdb/SparqlQueryStats.py
- askomics/libaskomics/source_file/SourceFile.py
- askomics/sparql/abstractionCategoriesEntityUserQuery.sparql
- askomics/sparql/privateQueryTemplate.rq
- askomics/sparql/publicQueryTemplate.rq
- askomics/sparql/usersQueryTemplate.rq
- askomics/static/js/AskomicsUser.js
- askomics/static/js/MainAskomics.js
- askomics/static/js/integration.js
- askomics/templates/index.pt
Now, 3 subclass of SparqlQuery:
- SparqlQueryGraph : contain all sparql query to extract data
- SparqlQueryAuth: contain sparql query for login/logout/signup
- SparqlQueryStats: contain query for statistic
These class doesen't use the template.sparql
> Statistic and SourceFile refactoring

- start.sh
Uncomment the line to lauch gulp in start script
> uncomment gulp

- askomics/libaskomics/ParamManager.py
- askomics/libaskomics/SourceFileConvertor.py
- askomics/libaskomics/source_file/SourceFile.py
- askomics/libaskomics/source_file/SourceFileGff.py
- askomics/libaskomics/source_file/SourceFileTsv.py
- askomics/libaskomics/source_file/SourceFileTtl.py
- askomics/static/js/MainAskomics.js
- askomics/static/js/integration.js
- askomics/templates/index.pt
* create unique URI for each Feature if not exist (CDS/Exon, etc...)
* encode/decode uri according the use
* fix bug when reading all entities (relations and sub entities are omitted)
* avoid redundancy
* create relation Parent_<targettype> and Derived_From_<targettype> to clear visualization
* test on : BOL.seq.20110802.chr_check.gff,Brassica_oleracea.v2.1.34.gff3, Brassica_rapa.IVFCAASv1.24.gff3,Danio_rerio.GRCz10.87.chromosome.gff3,TAIR10_GFF3_genes_transposons.gff
> Improve GFF loader

- Dockerfile
- askomics/libaskomics/ParamManager.py
- askomics/libaskomics/source_file/SourceFile.py
- configs/development.template.ini
- configs/production.template.ini
- configs/production.virtuoso.ini
- startAskomics.sh
- startAskomics_docker.sh
- update Dockerfile
- if URI start with a digit, concat `URI_` before (function `encodeToRDFURI` and `decodeToRDFURI`)
> Dockerfile

- askomics/ask_view.py
- askomics/libaskomics/SourceFileConvertor.py
- askomics/libaskomics/rdfdb/QueryLauncher.py
- askomics/libaskomics/source_file/SourceFile.py
- askomics/libaskomics/source_file/SourceFileGff.py
- askomics/static/js/app/objects/node/AskomicsNode.js
- askomics/test/askView_test.py
- askomics/test/interface_tps.py
- Keep file extension
- Guess file type with their extensions or with a optional value : forced_type (used in [asko-cli](https://github.com/askomics/asko-cli) with galaxy, because galaxy files have a .dat extension)
> SourceFile improvment

- .gitignore
- Dockerfile
- askomics/ask_view.py
- askomics/static/js/app/core/IHMLocal.js
- askomics/test/askView_test.py
- startAskomics.sh
Dockerfile
------------
- One `npm install` for all npm packages
startAskomics.sh
---------------------
If environment variables are set (`$TRIPLESTORE_ENDPOINT` and `$ASKOMICS_LOAD_URL`), create a custom.ini file with the modified parameters. Used for docker-compose.
Signup
-------
FIX Bug: Reload page when user create an account
> Start script + bugfix

- askomics/ask_view.py
- askomics/libaskomics/Security.py
- askomics/libaskomics/rdfdb/SparqlQueryAuth.py
User can login with only the APIkey, without the username
> Apikey without username

- askomics/libaskomics/source_file/SourceFileTsv.py
- askomics/static/src/js/core/AskomicsForceLayoutManager.js
- askomics/static/src/js/view/AskomicsNodeView.js
- askomics/static/src/js/view/AskomicsObjectView.js
- askomics/static/src/templates/index.pt
- remove refreshNode
- fix reset filter
- remove dead code
> Fix reset filter

- askomics/ask_view.py
- askomics/libaskomics/Security.py
- askomics/libaskomics/rdfdb/SparqlQueryAuth.py
- askomics/static/src/js/core/AskomicsUser.js
> Login with email

- askomics/libaskomics/source_file/SourceFile.py
- askomics/static/src/js/view/integration.js
- askomics/test/askView_test.py
When a user upload a file, replace non alphanumeric characters to a `_`. This allow upload and intetgration of any filename
> allow integration of file with non aplhanum characters

- askomics/__init__.py
- askomics/ask_view.py
- askomics/libaskomics/SourceFileConvertor.py
- askomics/libaskomics/source_file/SourceFile.py
- askomics/libaskomics/source_file/SourceFileBed.py
- askomics/libaskomics/source_file/SourceFileGff.py
- askomics/static/src/js/view/integration.js
- askomics/static/src/templates/handlebars/bed_form.hbs
- askomics/static/src/templates/upload.pt
- setup.py
- startAskomics.sh
This PR implement import of Bed files.
User provide a bed file, an entity name, and a taxon.
AskOmics store information about chrom, start, and, strand, name and score. Other columns of the file (7 to 12) are ignored (not relevant in AskOmics).
> Bed Import

- askomics/__init__.py
- askomics/ask_view.py
- askomics/libaskomics/SourceFileConvertor.py
- askomics/libaskomics/TripleStoreExplorer.py
- askomics/libaskomics/rdfdb/SparqlQueryGraph.py
- askomics/libaskomics/source_file/SourceFile.py
- askomics/libaskomics/source_file/SourceFileBed.py
- askomics/libaskomics/source_file/SourceFileGff.py
- askomics/libaskomics/source_file/SourceFileTsv.py
- askomics/static/src/js/view/integration.js
- askomics/static/src/templates/handlebars/bed_form.hbs
- askomics/static/src/templates/handlebars/csv_form.hbs
- askomics/static/src/templates/handlebars/gff_form.hbs
- askomics/test/askView_test.py
- startAskomics.sh
- set metadata into the triple store to retrieve all prefix uri and propose them on IHM
`:Personne displaySetting:prefixUri "http://www.test.com/"^^xsd:string .`
- define new IHM to propose all possible prefix value for start_entity and relation entity
> Overload askomics.prefix URI

- askomics/libaskomics/integration/AbstractedRelation.py
- askomics/libaskomics/source_file/SourceFileTsv.py
- askomics/static/src/js/core/AskomicsUserAbstraction.js
- askomics/static/src/js/objects/GraphObject.js
- user can specified in the header tsv file a relation like rdf:type@EntityName
> fix #207 issue. reconize ':' charactere in the header tsv file

- askomics/libaskomics/source_file/SourceFileGff.py
- configs/production.graphdb.ini
The bug was detect with graphDB
> GraphDB prod + Fix bug

- askomics/libaskomics/JobManager.py
- askomics/libaskomics/ParamManager.py
- askomics/static/src/js/core/AskomicsUser.js
- askomics/test/JobManager_test.py
- askomics/test/ParamManager_test.py
> Imporve session management + JobManager tests

- askomics/upload.py
Remove rename of file when exist because it doesnt work ;-) Because huge files are splited
> Fix bug when user upload huge file

- askomics/test/upload_test.py
- askomics/upload.py
Fix bug when user upload a huge file.
> Fix upload of big files

- askomics/static/src/js/objects/GraphObject.js
I merged the 17.09 branch into the master branch
> Fix Upload probleme

- askomics/ask_view.py
- askomics/static/modules/build_module_ttl_from_endpoint.py
- askomics/static/src/js/objects/link/AskomicsLink.js
- askomics/static/src/js/objects/link/AskomicsPositionableLink.js
- update script generation askomics abstraction to discover new endpoint
> - fix bug with sparql request generation

- askomics/ask_view.py
- askomics/static/modules/go_local.ttl
- askomics/static/src/js/objects/node/AskomicsNode.js
- askomics/static/src/js/objects/node/GraphNode.js
- askomics/static/src/js/view/AskomicsNodeView.js
- add ttl to manage go in local
>  fix bug eye on uri

- askomics/ask_view.py
- askomics/test/askView_test.py
> Fix exception handling + some flake8

- askomics/ask_view.py
- askomics/libaskomics/Security.py
- askomics/static/src/js/core/AskomicsUser.js
- askomics/static/src/js/core/IHMLocal.js
- askomics/static/src/templates/handlebars/admin_users.hbs
- askomics/test/askView_test.py
- configs/askomics.ini.template
- configs/tests.ini
some fixes for v18.10.1
fix #295 
fix #296 
fix #297 
fix #319 
fix #320 
fix #299
> 18.10.1 fixes

- askomics/libaskomics/LdapAuth.py
- docs/index.rst
- docs/tutorial.md
adding a `tutorial.md` file and an `images` folder in the docs directory
> Docs for tutorial

- askomics/__init__.py
- askomics/libaskomics/source_file/SourceFileBed.py
- askomics/libaskomics/source_file/SourceFileGff.py
- askomics/libaskomics/source_file/SourceFileTsv.py
- askomics/static/src/js/core/AskomicsGraphBuilder.js
- askomics/static/src/js/objects/node/GraphNode.js
- askomics/static/src/js/view/AskomicsNodeView.js
- askomics/static/src/js/view/AskomicsResultsView.js
- BED/GFF positionables queries
- diplay label and not uri by default
- display uri links with just label
- ...
> some fixes

- README.md
- askomics/static/src/js/objects/link/AskomicsPositionableLink.js
message "the repo is deprecated"
> Deprecated message
